# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f90280aa4070f1e529f46675bb9cdd9d9af716d57c13408f8ea72644a26c6042a0f1bb3009fe631da264d2d5d40e8bbf66a84225fdbc572838a824ab5c1970ec

test:
  secret_key_base: a38af9a08caac2c16782a801374f6f4049f57dd545ecf26518e4c4f739e00520bed6e1b279a9a03f36fe9444722e7580b160b796a9bf3adce9fe9cde5f205148

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
